"""SystemVerilog backend for the stateless RedC compute graph."""

from __future__ import annotations

import re

from ..ir import Graph, IRType
from ..parser import CompileError

SYMBOLS = {
    "add": "+",
    "sub": "-",
    "mul": "*",
    "div": "/",
    "mod": "%",
    "and": "&",
    "or": "|",
    "xor": "^",
    "eq": "==",
    "ne": "!=",
    "lt": "<",
    "le": "<=",
    "gt": ">",
    "ge": ">=",
}


def _declaration(typ: IRType) -> str:
    signed = " signed" if typ.signed else ""
    width = "" if typ.width == 1 else f" [{typ.width - 1}:0]"
    return f"logic{signed}{width}"


def _literal(bits: int, typ: IRType) -> str:
    if typ.width == 1:
        return f"1'b{bits & 1}"
    signed = "s" if typ.signed else ""
    return f"{typ.width}'{signed}h{bits & typ.mask:x}"


def _module_name(name: str) -> str:
    if not re.fullmatch(r"[a-zA-Z_][a-zA-Z0-9_]*", name):
        raise CompileError("SystemVerilog module name must be an identifier")
    return name


def emit_systemverilog(graph: Graph, module: str = "redc_main") -> str:
    """Emit a single combinational SystemVerilog module.

    Every IR node is represented by a continuously assigned signal. There are
    no procedural blocks, latches, registers, clocks, or implicit memories.
    """
    module = _module_name(module)
    graph.validate()
    nodes = graph.live_nodes()
    references = {
        node["id"]: node["name"] if node["op"] == "input" else f"n{node['id']}"
        for node in nodes
    }
    lines = [
        "// Generated by RedC from redc.comb.v1.",
        "// Pure combinational logic: hold inputs stable until outputs settle.",
        f"module {module} (",
    ]
    ports = [
        f"    input {_declaration(IRType(**port['type']))} {port['name']}"
        for port in graph.inputs
    ]
    ports.extend(
        f"    output {_declaration(IRType(**port['type']))} {port['name']}"
        for port in graph.outputs
    )
    lines.extend([",\n".join(ports), ");"])

    for node in nodes:
        if node["op"] != "input":
            lines.append(
                f"    {_declaration(IRType(**node['type']))} {references[node['id']]};"
            )

    for node in nodes:
        operation = node["op"]
        typ = IRType(**node["type"])
        if operation == "input":
            continue
        arguments = [references[node_id] for node_id in node["args"]]
        if operation == "const":
            expression = _literal(node["value"], typ)
        elif operation == "mux":
            expression = f"({arguments[0]} ? {arguments[1]} : {arguments[2]})"
        elif operation == "cast":
            source_type = IRType(**graph.nodes[node["args"][0]]["type"])
            if typ.boolean:
                expression = f"({arguments[0]} != {_literal(0, source_type)})"
            else:
                cast = "$signed" if source_type.signed else "$unsigned"
                expression = f"{cast}({arguments[0]})"
        elif operation in {"not", "neg", "inv"}:
            symbol = {"not": "!", "neg": "-", "inv": "~"}[operation]
            expression = f"({symbol}{arguments[0]})"
        elif operation in {"shl", "shr"}:
            symbol = "<<" if operation == "shl" else ">>>" if typ.signed else ">>"
            expression = f"({arguments[0]} {symbol} {arguments[1]})"
        elif operation in SYMBOLS:
            expression = f"({arguments[0]} {SYMBOLS[operation]} {arguments[1]})"
            if operation in {"div", "mod"}:
                expression = (
                    f"({arguments[1]} == {_literal(0, typ)}) "
                    f"? {_literal(0, typ)} : {expression}"
                )
        else:
            raise CompileError(f"no SystemVerilog emission rule for {operation}")
        lines.append(f"    assign {references[node['id']]} = {expression};")

    for port in graph.outputs:
        lines.append(f"    assign {port['name']} = {references[port['node']]};")
    lines.extend(["endmodule", ""])
    return "\n".join(lines)
