"""SystemVerilog backend for the RedC compute graph.

Combinational graphs emit exactly as before: typed ``logic`` ports and pure
continuous assignments, no procedural blocks. A sequential graph (one that
contains ``register`` nodes) additionally gets an implicit ``clk``/``rst`` pair
and a single ``always_ff`` block that advances every register on the clock edge
and resets it to its ``init`` value. The start/done handshake signals are just
ordinary ports and logic, so nothing special is needed for them here: the
module idles until ``start`` is pulsed, raises ``done`` for exactly one cycle on
completion, then returns to idle and may be started again without a reset.
"""

from __future__ import annotations

import re

from ..ir import Graph, IRType
from ..parser import CompileError

SYMBOLS = {
    "add": "+",
    "sub": "-",
    "mul": "*",
    "div": "/",
    "mod": "%",
    "and": "&",
    "or": "|",
    "xor": "^",
    "eq": "==",
    "ne": "!=",
    "lt": "<",
    "le": "<=",
    "gt": ">",
    "ge": ">=",
}


def _declaration(typ: IRType) -> str:
    signed = " signed" if typ.signed else ""
    width = "" if typ.width == 1 else f" [{typ.width - 1}:0]"
    return f"logic{signed}{width}"


def _literal(bits: int, typ: IRType) -> str:
    if typ.width == 1:
        return f"1'b{bits & 1}"
    signed = "s" if typ.signed else ""
    return f"{typ.width}'{signed}h{bits & typ.mask:x}"


def _module_name(name: str) -> str:
    if not re.fullmatch(r"[a-zA-Z_][a-zA-Z0-9_]*", name):
        raise CompileError("SystemVerilog module name must be an identifier")
    return name


def _expression(graph: Graph, node: dict, references: dict[int, str]) -> str:
    """Render one combinational node as a SystemVerilog expression."""
    operation = node["op"]
    typ = IRType(**node["type"])
    arguments = [references[node_id] for node_id in node["args"]]
    if operation == "const":
        return _literal(node["value"], typ)
    if operation == "mux":
        return f"({arguments[0]} ? {arguments[1]} : {arguments[2]})"
    if operation == "cast":
        source_type = IRType(**graph.nodes[node["args"][0]]["type"])
        if typ.boolean:
            return f"({arguments[0]} != {_literal(0, source_type)})"
        cast = "$signed" if source_type.signed else "$unsigned"
        return f"{cast}({arguments[0]})"
    if operation in {"not", "neg", "inv"}:
        symbol = {"not": "!", "neg": "-", "inv": "~"}[operation]
        return f"({symbol}{arguments[0]})"
    if operation in {"shl", "shr"}:
        symbol = "<<" if operation == "shl" else ">>>" if typ.signed else ">>"
        return f"({arguments[0]} {symbol} {arguments[1]})"
    if operation in SYMBOLS:
        expression = f"({arguments[0]} {SYMBOLS[operation]} {arguments[1]})"
        if operation in {"div", "mod"}:
            expression = (
                f"({arguments[1]} == {_literal(0, typ)}) "
                f"? {_literal(0, typ)} : {expression}"
            )
        return expression
    raise CompileError(f"no SystemVerilog emission rule for {operation}")


def emit_systemverilog(graph: Graph, module: str = "redc_main") -> str:
    """Emit a single SystemVerilog module for the graph.

    A combinational graph becomes pure continuous assignments. A sequential
    graph additionally declares ``clk``/``rst`` and drives its registers from an
    ``always_ff`` block; every other node remains a continuously assigned signal.
    """
    module = _module_name(module)
    graph.validate()
    nodes = graph.live_nodes()
    registers = [node for node in nodes if node["op"] == "register"]
    sequential = bool(registers)
    references = {
        node["id"]: node["name"]
        if node["op"] == "input"
        else f"r{node['id']}"
        if node["op"] == "register"
        else f"n{node['id']}"
        for node in nodes
    }

    if sequential:
        lines = [
            "// Generated by RedC from redc.seq.v1.",
            "// Sequential logic: pulse `start` while idle, hold inputs stable, read",
            "// outputs on the one cycle `done` is high; the module then returns to",
            "// idle. `start` while busy is ignored. `rst` (async, active high)",
            "// loads every register's init value.",
            f"module {module} (",
        ]
        ports = ["    input logic clk", "    input logic rst"]
    else:
        lines = [
            "// Generated by RedC from redc.comb.v1.",
            "// Pure combinational logic: hold inputs stable until outputs settle.",
            f"module {module} (",
        ]
        ports = []
    ports.extend(
        f"    input {_declaration(IRType(**port['type']))} {port['name']}"
        for port in graph.inputs
    )
    ports.extend(
        f"    output {_declaration(IRType(**port['type']))} {port['name']}"
        for port in graph.outputs
    )
    lines.extend([",\n".join(ports), ");"])

    for node in nodes:
        if node["op"] != "input":
            lines.append(
                f"    {_declaration(IRType(**node['type']))} {references[node['id']]};"
            )

    for node in nodes:
        if node["op"] in {"input", "register"}:
            continue
        lines.append(f"    assign {references[node['id']]} = {_expression(graph, node, references)};")

    if sequential:
        lines.append("    always_ff @(posedge clk or posedge rst) begin")
        lines.append("        if (rst) begin")
        for node in registers:
            typ = IRType(**node["type"])
            lines.append(
                f"            {references[node['id']]} <= {_literal(node['init'], typ)};"
            )
        lines.append("        end else begin")
        for node in registers:
            next_ref = references[node["args"][0]]
            enable_ref = references[node["args"][1]]
            lines.append(
                f"            if ({enable_ref}) {references[node['id']]} <= {next_ref};"
            )
        lines.append("        end")
        lines.append("    end")

    for port in graph.outputs:
        lines.append(f"    assign {port['name']} = {references[port['node']]};")
    lines.extend(["endmodule", ""])
    return "\n".join(lines)
