start: function

function: type NAME "(" parameters ")" "{" return_statement "}"

parameters: parameter ("," parameter)*
parameter: type NAME

return_statement: "return" expr ";"

?expr: expr "+" atom -> add
     | atom

?atom: NAME         -> variable
     | INT          -> integer
     | "(" expr ")"

type: "uint8" -> uint8_type

NAME: /[a-zA-Z_][a-zA-Z0-9_]*/

%import common.INT
%import common.WS
%ignore WS
%ignore /\/\/[^\n]*/